/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package estoque;

import views.viewGrupos;
import views.viewPrateleiras;
import views.viewProdutos;
import views.viewSecoes;

/**
 *
 * @author nmpetry
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrupos = new javax.swing.JButton();
        btnProdutos = new javax.swing.JButton();
        btnSecoes = new javax.swing.JButton();
        btnPrateleiras = new javax.swing.JButton();
        lblGrupos = new javax.swing.JLabel();
        lblProdutos = new javax.swing.JLabel();
        lblSecoes = new javax.swing.JLabel();
        lblPrateleiras = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        rltSecoes = new javax.swing.JMenu();
        rltGrupos = new javax.swing.JMenuItem();
        rltProdutos = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        rltPrateleiras = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnGrupos.setBackground(new java.awt.Color(255, 255, 255));
        btnGrupos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnGrupos.setForeground(new java.awt.Color(255, 255, 255));
        btnGrupos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/grupos.png"))); // NOI18N
        btnGrupos.setToolTipText("Grupos");
        btnGrupos.setBorderPainted(false);
        btnGrupos.setPreferredSize(new java.awt.Dimension(250, 210));
        btnGrupos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGruposActionPerformed(evt);
            }
        });

        btnProdutos.setBackground(new java.awt.Color(255, 255, 255));
        btnProdutos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnProdutos.setForeground(new java.awt.Color(255, 255, 255));
        btnProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/produtos.png"))); // NOI18N
        btnProdutos.setToolTipText("Produtos");
        btnProdutos.setBorderPainted(false);
        btnProdutos.setPreferredSize(new java.awt.Dimension(250, 210));
        btnProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdutosActionPerformed(evt);
            }
        });

        btnSecoes.setBackground(new java.awt.Color(255, 255, 255));
        btnSecoes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSecoes.setForeground(new java.awt.Color(255, 255, 255));
        btnSecoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/secoes.png"))); // NOI18N
        btnSecoes.setToolTipText("Seções");
        btnSecoes.setBorderPainted(false);
        btnSecoes.setPreferredSize(new java.awt.Dimension(250, 210));
        btnSecoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSecoesActionPerformed(evt);
            }
        });

        btnPrateleiras.setBackground(new java.awt.Color(255, 255, 255));
        btnPrateleiras.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPrateleiras.setForeground(new java.awt.Color(255, 255, 255));
        btnPrateleiras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/prateleiras.png"))); // NOI18N
        btnPrateleiras.setToolTipText("Prateleiras");
        btnPrateleiras.setBorderPainted(false);
        btnPrateleiras.setPreferredSize(new java.awt.Dimension(250, 210));
        btnPrateleiras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrateleirasActionPerformed(evt);
            }
        });

        lblGrupos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblGrupos.setForeground(new java.awt.Color(255, 255, 255));
        lblGrupos.setText("GRUPOS");

        lblProdutos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblProdutos.setForeground(new java.awt.Color(255, 255, 255));
        lblProdutos.setText("PRODUTOS");

        lblSecoes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSecoes.setForeground(new java.awt.Color(255, 255, 255));
        lblSecoes.setText("SEÇÕES");

        lblPrateleiras.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPrateleiras.setForeground(new java.awt.Color(255, 255, 255));
        lblPrateleiras.setText("PRATELEIRAS");

        rltSecoes.setText("Relatórios");

        rltGrupos.setText("Grupos");
        rltGrupos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rltGruposActionPerformed(evt);
            }
        });
        rltSecoes.add(rltGrupos);

        rltProdutos.setText("Produtos");
        rltSecoes.add(rltProdutos);

        jMenuItem1.setText("Seções");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        rltSecoes.add(jMenuItem1);

        rltPrateleiras.setText("Prateleiras");
        rltSecoes.add(rltPrateleiras);

        jMenuBar1.add(rltSecoes);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSecoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                        .addComponent(btnPrateleiras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGrupos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addComponent(lblGrupos)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnProdutos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblProdutos)
                                .addGap(83, 83, 83)))))
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(lblSecoes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblPrateleiras)
                .addGap(90, 90, 90))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGrupos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblGrupos))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblProdutos)))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrateleiras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSecoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSecoes)
                    .addComponent(lblPrateleiras))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGruposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGruposActionPerformed
        // TODO add your handling code here:
        viewGrupos grupos = new viewGrupos();
        grupos.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnGruposActionPerformed

    private void btnProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdutosActionPerformed
        // TODO add your handling code here:
        viewProdutos produtos = new viewProdutos();
        produtos.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnProdutosActionPerformed

    private void btnSecoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSecoesActionPerformed
        // TODO add your handling code here:
        viewSecoes secoes = new viewSecoes();
        secoes.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSecoesActionPerformed

    private void btnPrateleirasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrateleirasActionPerformed
        // TODO add your handling code here:
        viewPrateleiras prateleiras = new viewPrateleiras();
        prateleiras.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPrateleirasActionPerformed

    private void rltGruposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rltGruposActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rltGruposActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGrupos;
    private javax.swing.JButton btnPrateleiras;
    private javax.swing.JButton btnProdutos;
    private javax.swing.JButton btnSecoes;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel lblGrupos;
    private javax.swing.JLabel lblPrateleiras;
    private javax.swing.JLabel lblProdutos;
    private javax.swing.JLabel lblSecoes;
    private javax.swing.JMenuItem rltGrupos;
    private javax.swing.JMenuItem rltPrateleiras;
    private javax.swing.JMenuItem rltProdutos;
    private javax.swing.JMenu rltSecoes;
    // End of variables declaration//GEN-END:variables
}
